CREATE TABLE cn_posts (
  `id` int,
  `username` varchar(255),
  `avatar_template` varchar(255),
  `created_at` datetime,
  `cooked` text,
  `post_number` int,
  `post_type` int,
  `updated_at` datetime,
  `reply_count` int,
  `reply_to_post_number` int,
  `quote_count` int,
  `incoming_link_count` int,
  `reads` int,
  `readers_count` int,
  `score` float,
  `yours` boolean,
  `topic_id` int,
  `topic_slug` varchar(255),
  `version` int,
  `can_edit` boolean,
  `can_delete` boolean,
  `can_recover` boolean,
  `can_see_hidden_post` boolean,
  `can_wiki` boolean,
  `bookmarked` boolean,
  `raw` text,
  `moderator` boolean,
  `admin` boolean,
  `staff` boolean,
  `user_id` int,
  `hidden` boolean,
  `trust_level` int,
  `user_deleted` boolean,
  `can_view_edit_history` boolean,
  `wiki` boolean,
  `can_accept_answer` boolean,
  `can_unaccept_answer` boolean,
  `accepted_answer` boolean,
  `topic_accepted_answer` boolean,

  `en_id` int,
  `translated` text,
  PRIMARY KEY (id)
);

CREATE TABLE cn_topics (
  `id` int,
  `title` varchar(255),
  `fancy_title` varchar(255),
  `slug` varchar(255),
  `posts_count` int,
  `reply_count` int,
  `highest_post_number` int,
  `created_at` datetime,
  `last_posted_at` datetime,
  `archetype` varchar(255),
  `pinned` boolean,
  `visible` boolean,
  `closed` boolean,
  `archived` boolean,
  `views` int,
  `like_count` int,
  `has_summary` boolean,
  `category_id` int,
  `pinned_globally` boolean,
  `has_accepted_answer` boolean,

  `en_id` int,
  `translated_title` text,
  PRIMARY KEY (id)
);

CREATE TABLE sync_progress (
  `cn_topic_id` int,
  `en_topic_id` int default -1,
  `cn_title` varchar(255),
  `cn_created_at` datetime,
  `translate_state` int default 0 comment '0 - not translate, 1 - translating, 2 - translated',
  `translate_at` datetime default '1980-01-01 00:00:00',
  PRIMARY KEY (cn_topic_id)
)